// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
import axios from '../node_modules/axios/lib/axios.js'

const {
  Axios,
  AxiosError,
  CanceledError,
  isCancel,
  CancelToken,
  VERSION,
  all,
  Cancel,
  isAxiosError,
  spread,
  toFormData,
  AxiosHeaders,
  HttpStatusCode,
  formToJSON,
  getAdapter,
  mergeConfig
} = axios

export {
  all,
  Axios,
  AxiosError,
  AxiosHeaders,
  Cancel,
  CanceledError,
  CancelToken,
  axios as default,
  formToJSON,
  getAdapter,
  HttpStatusCode,
  isAxiosError,
  isCancel,
  mergeConfig,
  spread,
  toFormData,
  VERSION
}

export type {
  AddressFamily,
  AxiosAdapter,
  AxiosBasicCredentials,
  AxiosDefaults,
  AxiosHeaderValue,
  AxiosInstance,
  AxiosInterceptorManager,
  AxiosInterceptorOptions,
  AxiosProgressEvent,
  AxiosPromise,
  AxiosProxyConfig,
  AxiosRequestConfig,
  AxiosRequestHeaders,
  AxiosResponse,
  AxiosResponseHeaders,
  AxiosResponseTransformer,
  AxiosStatic,
  Canceler,
  CancelStatic,
  CancelTokenSource,
  CancelTokenStatic,
  CreateAxiosDefaults,
  CustomParamsSerializer,
  FormDataVisitorHelpers,
  FormSerializerOptions,
  GenericAbortSignal,
  GenericFormData,
  GenericHTMLFormElement,
  HeadersDefaults,
  InternalAxiosRequestConfig,
  LookupAddress,
  LookupAddressEntry,
  Method,
  ParamEncoder,
  ParamsSerializerOptions,
  RawAxiosRequestConfig,
  RawAxiosRequestHeaders,
  RawAxiosResponseHeaders,
  responseEncoding,
  ResponseType,
  SerializerOptions,
  SerializerVisitor,
  TransitionalOptions
} from 'axios'
